### ISSUE TITLE
Gui problem on CS 6 from 09Jan19

### ISSUE THREAD

**Issue by YohannEude** [code-saturne/code_saturne#31]
Hello,

I would like to test the current version of CS but the GUI doesn't start. I have the following error when I try to run the GUI:

Traceback (most recent call last):
  File "/home/yohann-ws2/Code_Saturne/6.0-alpha_09Jan19/code_saturne-6.0-alpha/arch/Linux_x86_64/bin/code_saturne", line 76, in <module>
    retcode = cs.execute()
  File "/home/yohann-ws2/Code_Saturne/6.0-alpha_09Jan19/code_saturne-6.0-alpha/arch/Linux_x86_64/lib/python2.7/site-packages/code_saturne/cs_script.py", line 91, in execute
    return self.commands[command](options)
  File "/home/yohann-ws2/Code_Saturne/6.0-alpha_09Jan19/code_saturne-6.0-alpha/arch/Linux_x86_64/lib/python2.7/site-packages/code_saturne/cs_script.py", line 150, in gui
    return cs_gui.main(options, self.package)
  File "/home/yohann-ws2/Code_Saturne/6.0-alpha_09Jan19/code_saturne-6.0-alpha/arch/Linux_x86_64/lib/python2.7/site-packages/code_saturne/cs_gui.py", line 194, in main
    from code_saturne.Base.MainView import MainView
  File "/home/yohann-ws2/Code_Saturne/6.0-alpha_09Jan19/code_saturne-6.0-alpha/arch/Linux_x86_64/lib/python2.7/site-packages/code_saturne/Base/MainView.py", line 77, in <module>
    from code_saturne.Base.BrowserView import BrowserView
  File "/home/yohann-ws2/Code_Saturne/6.0-alpha_09Jan19/code_saturne-6.0-alpha/arch/Linux_x86_64/lib/python2.7/site-packages/code_saturne/Base/BrowserView.py", line 67, in <module>
    _fromUtf8 = QString.fromUtf8
NameError: name 'QString' is not defined

How can I fix that?

Greetings,

Yohann

**Comment by YvanFournier** [comment]
Hello,

I also observed this yesterday, and fixed this earlier today in commit 262d6d4b..
