### ISSUE TITLE
Core dump from "Manage user functions within the SRC folder"

### ISSUE THREAD

**Issue by jcharris** [code-saturne/code_saturne#43]
Testing feature "Manage user functions within the SRC folder" crashes GUI (similar outcome for trying to view log files), with the following error printed to output:

`[11:21:04] : DATA/ $ ./SaturneGUI setup.xml 
Traceback (most recent call last):
  File "/home/jcharris/Articles/OM/FINAL_RESULTS/lib/python2.7/site-packages/code_saturne/Base/MainView.py", line 886, in fileEditorOpen
    from code_saturne.Base.QFileEditor import QFileEditor
  File "/home/jcharris/Articles/OM/FINAL_RESULTS/lib/python2.7/site-packages/code_saturne/Base/QFileEditor.py", line 279, in <module>
    class QFileEditor(QtGui.QMainWindow):
AttributeError: 'module' object has no attribute 'QMainWindow'
./SaturneGUI : ligne 7 :  7260 Abandon                 (core dumped) \code_saturne gui $@
`

**Comment by YvanFournier** [comment]
Worked in PyQt4, failed in PyQt5.

Fixed in master (commit a1155be7) and v6.0 (commit 6ebb0f641).
